# ================================================
# Container Security Report Generator
# ================================================
import json
import datetime
import os

def generate_report(scan_results):
    """Generate a professional security report"""

    timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    report_date = datetime.datetime.now().strftime("%Y-%m-%d")

    report = f"""
================================================================================
                    CONTAINER SECURITY ASSESSMENT REPORT
================================================================================
Report Date    : {timestamp}
Generated By   : Container Security Framework v1.0
Classification : CONFIDENTIAL
================================================================================

EXECUTIVE SUMMARY
-----------------
Total Images Scanned : {scan_results['total_images']}
Clean Images         : {scan_results['clean']}
Issues Found         : {scan_results['issues']}
Critical Findings    : {scan_results['critical']}
High Findings        : {scan_results['high']}

RISK RATING: {get_risk_rating(scan_results['critical'], scan_results['high'])}

================================================================================
DETAILED FINDINGS
================================================================================
"""

    for finding in scan_results.get('findings', []):
        report += f"""
Image    : {finding['image']}
Severity : {finding['severity']}
Issue    : {finding['description']}
Action   : {finding['action']}
{'-' * 60}
"""

    report += f"""
================================================================================
RECOMMENDATIONS
================================================================================
1. Update all base images to latest patched versions
2. Remove unnecessary packages from containers
3. Enforce non-root user in all Dockerfiles
4. Enable read-only filesystem where possible
5. Implement image signing and verification
6. Schedule weekly automated scans
7. Block deployment of images with CRITICAL vulnerabilities

================================================================================
END OF REPORT
================================================================================
"""
    # Save report
    os.makedirs('reports', exist_ok=True)
    filename = f"reports/security-report-{report_date}.txt"
    
    # FIXED: Added encoding='utf-8' so Python can handle emojis inside text files smoothly on Windows
    with open(filename, 'w', encoding='utf-8') as f:
        f.write(report)

    print(report)
    print(f"[+] Report saved to: {filename}")
    return filename


def get_risk_rating(critical, high):
    if critical > 0:
        return "🔴 CRITICAL"
    elif high > 5:
        return "🟠 HIGH"
    elif high > 0:
        return "🟡 MEDIUM"
    else:
        return "🟢 LOW"


# Sample scan results for demo
if __name__ == "__main__":
    sample_results = {
        "total_images": 3,
        "clean": 2,
        "issues": 1,
        "critical": 0,
        "high": 2,
        "findings": [
            {
                "image": "secure-app:latest",
                "severity": "HIGH",
                "description": "Outdated SSL library detected",
                "action": "Update base image to python:3.11-slim"
            },
            {
                "image": "secure-app:latest",
                "severity": "HIGH",
                "description": "Missing HEALTHCHECK instruction",
                "action": "Add HEALTHCHECK to Dockerfile"
            }
        ]
    }
    generate_report(sample_results)